version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./userbasedb.sqlite:/app/userbasedb.sqlite
    environment:
      - FLASK_ENV=development
      - FLASK_APP=userbase:create_app()
    command: >
      /bin/sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
